- name: AppSec
  tribeDomain: Engineering
  lead: appsec.lead@example.com
- name: BI
  tribeDomain: Product
  lead: bi.lead@example.com
- name: Billing
  tribeDomain: Business
  lead: billing.lead@example.com
- name: Comms
  tribeDomain: Engineering
  lead: comms.lead@example.com
- name: Data
  tribeDomain: Engineering
  lead: data.lead@example.com
- name: Experimentation
  tribeDomain: Product
  lead: exp.lead@example.com
- name: Internal
  tribeDomain: Operations
  lead: internal.lead@example.com
- name: ML
  tribeDomain: Product
  lead: ml.lead@example.com
- name: Mobile
  tribeDomain: Product
  lead: mobile.lead@example.com
- name: Relevance
  tribeDomain: Product
  lead: relevance.lead@example.com
- name: Risk
  tribeDomain: Business
  lead: risk.lead@example.com
- name: SRE
  tribeDomain: Engineering
  lead: sre.lead@example.com
- name: Storefront
  tribeDomain: Business
  lead: storefront.lead@example.com
- name: Tooling
  tribeDomain: Engineering
  lead: tooling.lead@example.com
- name: Web
  tribeDomain: Product
  lead: web.lead@example.com
