/**
 * AIOps seed script — seeds InfraClusters, Apps, and AppDeployments from
 * the config YAML files (data inlined here to avoid a js-yaml dependency).
 *
 * IMPORTANT: run `npm run seed` (seed.ts) FIRST so squad keys exist.
 * Then run: npx ts-node src/scripts/seed-aiops.ts
 */

import dotenv from 'dotenv';
import path from 'path';
dotenv.config({ path: path.resolve(__dirname, '../config/.env') });
import '../src/config/env';
import { connectRedis } from '../src/config/redis';
import * as infraService from '../src/services/infra.service';
import * as appService from '../src/services/app.service';
import * as appstatusService from '../src/services/appstatus.service';
import * as squadService from '../src/services/squad.service';
import type { DeployState } from '../src/models/index';

// ── Infra clusters (from infra.yaml) ────────────────────────────────────────

const INFRA_CLUSTERS = [
  { platformId: 'backend-local-cluster',   name: 'Backend Local Cluster',  clusterId: 'CLUSTER001', environment: 'local', host: 'https://api.cluster001.intranet.example.com:6443', routeHostName: '.apps.cluster001.intranet.example.com:6443', platform: 'onprem',  platformType: 'OCP',      tokenId: 'TOKEN_ocp_1',  tags: { criticality: 'low',    datacenter: 'eu-fra-1', costCenter: 'CC-1001' } },
  { platformId: 'frontend-local-cluster',  name: 'Frontend Local Cluster', clusterId: 'CLUSTER002', environment: 'local', host: 'https://api.cluster002.intranet.example.com:6443', routeHostName: '.apps.cluster002.intranet.example.com:6443', platform: 'onprem',  platformType: 'OCP',      tokenId: 'TOKEN_ocp_2',  tags: { criticality: 'low',    datacenter: 'eu-fra-1', costCenter: 'CC-1001' } },
  { platformId: 'backend-dev-cluster',     name: 'Backend Dev Cluster',    clusterId: 'CLUSTER003', environment: 'dev',   host: 'https://api.cluster003.intranet.example.com:6443', routeHostName: '.apps.cluster003.intranet.example.com:6443', platform: 'onprem',  platformType: 'OCP',      tokenId: 'TOKEN_ocp_3',  tags: { criticality: 'low',    datacenter: 'eu-fra-1', costCenter: 'CC-1001' } },
  { platformId: 'backend-int-cluster',     name: 'Backend Int Cluster',    clusterId: 'CLUSTER004', environment: 'int',   host: 'https://api.cluster004.intranet.example.com:6443', routeHostName: '.apps.cluster004.intranet.example.com:6443', platform: 'onprem',  platformType: 'OCP',      tokenId: 'TOKEN_ocp_4',  tags: { criticality: 'low',    datacenter: 'eu-fra-1', costCenter: 'CC-1001' } },
  { platformId: 'backend-uat-cluster',     name: 'Backend UAT Cluster',    clusterId: 'CLUSTER005', environment: 'uat',   host: 'https://api.cluster005.intranet.example.com:6443', routeHostName: '.apps.cluster005.intranet.example.com:6443', platform: 'onprem',  platformType: 'OCP',      tokenId: 'TOKEN_ocp_5',  tags: { criticality: 'medium', datacenter: 'eu-fra-1', costCenter: 'CC-1001' } },
  { platformId: 'backend-prd-cluster',     name: 'Backend PRD Cluster',    clusterId: 'CLUSTER006', environment: 'prd',   host: 'https://api.cluster006.intranet.example.com:6443', routeHostName: '.apps.cluster006.intranet.example.com:6443', platform: 'onprem',  platformType: 'OCP',      tokenId: 'TOKEN_ocp_6',  tags: { criticality: 'high',   datacenter: 'eu-fra-1', costCenter: 'CC-1001' } },
  { platformId: 'frontend-uat-cluster',    name: 'Frontend UAT Cluster',   clusterId: 'CLUSTER007', environment: 'uat',   host: 'https://api.cluster007.intranet.example.com:6443', routeHostName: '.apps.cluster007.intranet.example.com:6443', platform: 'onprem',  platformType: 'OCP',      tokenId: 'TOKEN_ocp_7',  tags: { criticality: 'medium', datacenter: 'eu-fra-1', costCenter: 'CC-1001' } },
  { platformId: 'frontend-prd-cluster',    name: 'Frontend PRD Cluster',   clusterId: 'CLUSTER008', environment: 'prd',   host: 'https://api.cluster008.intranet.example.com:6443', routeHostName: '.apps.cluster008.intranet.example.com:6443', platform: 'onprem',  platformType: 'OCP',      tokenId: 'TOKEN_ocp_8',  tags: { criticality: 'high',   datacenter: 'eu-fra-1', costCenter: 'CC-1001' } },
  { platformId: 'backend-dev-gcp',         name: 'Backend GCP Dev',        clusterId: 'CLUSTER009', environment: 'dev',   host: '',                                                  routeHostName: '.apps.cluster009.intranet.example.com:6443', platform: 'cloud',   platformType: 'CloudRun', tokenId: 'TOKEN_GCP_9',  tags: { criticality: 'low',    region: 'us-central1',  costCenter: 'CC-2002' } },
  { platformId: 'backend-int-gcp',         name: 'Backend GCP Int',        clusterId: 'CLUSTER010', environment: 'int',   host: '',                                                  routeHostName: '.apps.cluster010.intranet.example.com:6443', platform: 'cloud',   platformType: 'CloudRun', tokenId: 'TOKEN_GCP_10', tags: { criticality: 'low',    region: 'us-central1',  costCenter: 'CC-2002' } },
  { platformId: 'backend-uat-gcp',         name: 'Backend GCP UAT',        clusterId: 'CLUSTER011', environment: 'uat',   host: '',                                                  routeHostName: '.apps.cluster011.intranet.example.com:6443', platform: 'cloud',   platformType: 'CloudRun', tokenId: 'TOKEN_GCP_11', tags: { criticality: 'medium', region: 'us-central1',  costCenter: 'CC-2002' } },
  { platformId: 'backend-prd-gcp',         name: 'Backend GCP PRD',        clusterId: 'CLUSTER012', environment: 'prd',   host: '',                                                  routeHostName: '.apps.cluster012.intranet.example.com:6443', platform: 'cloud',   platformType: 'CloudRun', tokenId: 'TOKEN_GCP_12', tags: { criticality: 'high',   region: 'us-central1',  costCenter: 'CC-2002' } },
  { platformId: 'data-pipeline-dev',       name: 'Data Pipeline Dev',      clusterId: 'CLUSTER013', environment: 'dev',   host: '',                                                  routeHostName: '.apps.cluster013.intranet.example.com:6443', platform: 'cloud',   platformType: 'CloudRun', tokenId: 'TOKEN_GCP_13', tags: { criticality: 'low',    region: 'us-central1',  costCenter: 'CC-2002' } },
  { platformId: 'data-pipeline-int',       name: 'Data Pipeline Int',      clusterId: 'CLUSTER014', environment: 'int',   host: '',                                                  routeHostName: '.apps.cluster014.intranet.example.com:6443', platform: 'cloud',   platformType: 'CloudRun', tokenId: 'TOKEN_GCP_14', tags: { criticality: 'low',    region: 'us-central1',  costCenter: 'CC-2002' } },
  { platformId: 'data-pipeline-uat',       name: 'Data Pipeline UAT',      clusterId: 'CLUSTER015', environment: 'uat',   host: '',                                                  routeHostName: '.apps.cluster015.intranet.example.com:6443', platform: 'cloud',   platformType: 'CloudRun', tokenId: 'TOKEN_GCP_15', tags: { criticality: 'medium', region: 'us-central1',  costCenter: 'CC-2002' } },
  { platformId: 'data-pipeline-prd',       name: 'Data Pipeline PRD',      clusterId: 'CLUSTER016', environment: 'prd',   host: '',                                                  routeHostName: '.apps.cluster016.intranet.example.com:6443', platform: 'cloud',   platformType: 'CloudRun', tokenId: 'TOKEN_GCP_16', tags: { criticality: 'high',   region: 'us-central1',  costCenter: 'CC-2002' } },
] as const;

// ── App tool URL helpers ──────────────────────────────────────────────────────

const ART  = (id: string) => `https://artifactory.example.com/ui/repos/tree/General/libs-release/com/example/${id}`;
const XRAY = (id: string) => `https://xray.example.com/ui/component/com.example:${id}`;
const COMP = (id: string) => `https://composition.example.com/apps/${id}`;
const SPLK = (id: string) => `https://splunk.example.com/app/search#search?q=index%3Dprd+app%3D${id}&earliest=-7d`;

// ── Apps (from appinfo.yaml) ─────────────────────────────────────────────────

const APP_DEFS = [
  // platform — Java 17
  { appId: 'auth-api',           squadKey: 'platform',        gitRepo: 'https://github.com/example/auth-api',           status: 'active',                      platforms: { intPlatform: 'backend-int-cluster',  uatPlatform: 'backend-uat-cluster',  prdPlatform: 'backend-prd-cluster'  }, urls: { intUrl: 'https://gw-int-auth-api.intranet.example.com',   uatUrl: 'https://gw-uat-auth-api.intranet.example.com',   prdUrl: 'https://gw-prd-auth-api.intranet.example.com'   }, probeHealth: '/health', probeInfo: '/info',   probeLiveness: '/health/liveness', probeReadiness: '/health/readiness', tags: { criticality: 'high',   pillar: 'platform' }, javaVersion: '17', javaComplianceStatus: 'compliant',     artifactoryUrl: ART('auth-api'),       xrayUrl: XRAY('auth-api'),       compositionViewerUrl: COMP('auth-api'),       splunkUrl: SPLK('auth-api') },
  { appId: 'config-service',     squadKey: 'platform',        gitRepo: 'https://github.com/example/config-service',     status: 'active',                      platforms: { intPlatform: 'backend-int-cluster',  uatPlatform: 'backend-uat-cluster',  prdPlatform: 'backend-prd-cluster'  }, urls: { intUrl: 'https://gw-int-config.intranet.example.com',     uatUrl: 'https://gw-uat-config.intranet.example.com',     prdUrl: 'https://gw-prd-config.intranet.example.com'     }, probeHealth: '/health',                                    probeReadiness: '/health/readiness', tags: { criticality: 'high',   pillar: 'platform' }, javaVersion: '17', javaComplianceStatus: 'compliant',     artifactoryUrl: ART('config-service'), xrayUrl: XRAY('config-service'), compositionViewerUrl: COMP('config-service'), splunkUrl: SPLK('config-service') },
  { appId: 'health-checker',     squadKey: 'platform',        gitRepo: 'https://github.com/example/health-checker',     status: 'active',                      platforms: { intPlatform: 'backend-int-gcp',                                          prdPlatform: 'backend-prd-gcp'      }, urls: { intUrl: 'https://gw-int-healthcheck.example.com',                                                           prdUrl: 'https://gw-prd-healthcheck.example.com'         }, probeHealth: '/health',                                                                                            tags: { criticality: 'medium', pillar: 'platform' },                                                               compositionViewerUrl: COMP('health-checker'),                                         splunkUrl: SPLK('health-checker') },
  // payments
  { appId: 'payments-api',       squadKey: 'payments',        gitRepo: 'https://github.com/example/payments-api',       status: 'active',                      platforms: { intPlatform: 'backend-int-cluster',  uatPlatform: 'backend-uat-cluster',  prdPlatform: 'backend-prd-cluster'  }, urls: { intUrl: 'https://gw-int-payments.intranet.example.com',   uatUrl: 'https://gw-uat-payments.intranet.example.com',   prdUrl: 'https://gw-prd-payments.intranet.example.com'   }, probeHealth: '/health', probeInfo: '/info',   probeLiveness: '/health/liveness', probeReadiness: '/health/readiness', tags: { criticality: 'high',   pillar: 'commerce', pci: 'true' }, javaVersion: '21', javaComplianceStatus: 'compliant',     artifactoryUrl: ART('payments-api'),   xrayUrl: XRAY('payments-api'),   compositionViewerUrl: COMP('payments-api'),   splunkUrl: SPLK('payments-api') },
  { appId: 'invoice-service',    squadKey: 'payments',        gitRepo: 'https://github.com/example/invoice-service',    status: 'active',                      platforms: { intPlatform: 'backend-int-gcp',      uatPlatform: 'backend-uat-gcp',      prdPlatform: 'backend-prd-gcp'      }, urls: { intUrl: 'https://gw-int-invoice.example.com',             uatUrl: 'https://gw-uat-invoice.example.com',             prdUrl: 'https://gw-prd-invoice.example.com'             }, probeHealth: '/health',                                    probeReadiness: '/health/readiness', tags: { criticality: 'high',   pillar: 'commerce' },  javaVersion: '17', javaComplianceStatus: 'compliant',     artifactoryUrl: ART('invoice-service'),xrayUrl: XRAY('invoice-service'),compositionViewerUrl: COMP('invoice-service'), splunkUrl: SPLK('invoice-service') },
  { appId: 'refund-worker',      squadKey: 'payments',        gitRepo: 'https://github.com/example/refund-worker',      status: 'active',                      platforms: { intPlatform: 'backend-int-gcp',      uatPlatform: 'backend-uat-gcp',      prdPlatform: 'backend-prd-gcp'      }, urls: { intUrl: 'https://gw-int-refund.example.com',              uatUrl: 'https://gw-uat-refund.example.com',              prdUrl: 'https://gw-prd-refund.example.com'              }, probeHealth: '/health',                                                                                            tags: { criticality: 'high',   pillar: 'commerce' },  javaVersion: '17', javaComplianceStatus: 'compliant',     artifactoryUrl: ART('refund-worker'),  xrayUrl: XRAY('refund-worker'),  compositionViewerUrl: COMP('refund-worker'),  splunkUrl: SPLK('refund-worker') },
  { appId: 'payments-admin-ui',  squadKey: 'payments',        gitRepo: 'https://github.com/example/payments-admin-ui',  status: 'active',                      platforms: { uatPlatform: 'frontend-uat-cluster',                                     prdPlatform: 'frontend-prd-cluster' }, urls: { uatUrl: 'https://gw-uat-payments-admin.intranet.example.com',                                               prdUrl: 'https://gw-prd-payments-admin.intranet.example.com' }, probeHealth: '/healthz',                                                                                         tags: { criticality: 'medium', pillar: 'commerce' },                                                               compositionViewerUrl: COMP('payments-admin-ui'),                                      splunkUrl: SPLK('payments-admin-ui') },
  // checkout
  { appId: 'checkout-web',       squadKey: 'checkout',        gitRepo: 'https://github.com/example/checkout-web',       status: 'active',                      platforms: { uatPlatform: 'frontend-uat-cluster',                                     prdPlatform: 'frontend-prd-cluster' }, urls: { uatUrl: 'https://gw-uat-checkout.intranet.example.com',                                                     prdUrl: 'https://gw-prd-checkout.intranet.example.com'   }, probeHealth: '/healthz',                                                                                           tags: { criticality: 'high',   pillar: 'commerce' },                                                               compositionViewerUrl: COMP('checkout-web'),                                           splunkUrl: SPLK('checkout-web') },
  { appId: 'cart-service',       squadKey: 'checkout',        gitRepo: 'https://github.com/example/cart-service',       status: 'active',                      platforms: { intPlatform: 'backend-int-cluster',  uatPlatform: 'backend-uat-cluster',  prdPlatform: 'backend-prd-cluster'  }, urls: { intUrl: 'https://gw-int-cart.intranet.example.com',       uatUrl: 'https://gw-uat-cart.intranet.example.com',       prdUrl: 'https://gw-prd-cart.intranet.example.com'       }, probeHealth: '/health',                                    probeReadiness: '/health/readiness', tags: { criticality: 'high',   pillar: 'commerce' },  javaVersion: '17', javaComplianceStatus: 'compliant',     artifactoryUrl: ART('cart-service'),   xrayUrl: XRAY('cart-service'),   compositionViewerUrl: COMP('cart-service'),   splunkUrl: SPLK('cart-service') },
  { appId: 'checkout-legacy',    squadKey: 'checkout',        gitRepo: 'https://github.com/example/checkout-legacy',    status: 'marked-for-decommissioning',  platforms: { prdPlatform: 'backend-prd-cluster'  },                                                                          urls: { prdUrl: 'https://gw-prd-checkout-legacy.intranet.example.com'                                              },                                probeHealth: '/health',                                                                                            tags: { criticality: 'low',    sunset: '2026-Q3' },   javaVersion: '8',  javaComplianceStatus: 'exempt',                                                                                                                                          splunkUrl: SPLK('checkout-legacy') },
  // identity
  { appId: 'auth-gateway',       squadKey: 'identity',        gitRepo: 'https://github.com/example/auth-gateway',       status: 'active',                      platforms: { intPlatform: 'backend-int-cluster',  uatPlatform: 'backend-uat-cluster',  prdPlatform: 'backend-prd-cluster'  }, urls: { intUrl: 'https://gw-int-auth.intranet.example.com',       uatUrl: 'https://gw-uat-auth.intranet.example.com',       prdUrl: 'https://gw-prd-auth.intranet.example.com'       }, probeHealth: '/health',               probeLiveness: '/health/liveness', probeReadiness: '/health/readiness',   tags: { criticality: 'high',   pillar: 'security' }, javaVersion: '17', javaComplianceStatus: 'compliant',     artifactoryUrl: ART('auth-gateway'),   xrayUrl: XRAY('auth-gateway'),   compositionViewerUrl: COMP('auth-gateway'),   splunkUrl: SPLK('auth-gateway') },
  { appId: 'user-directory',     squadKey: 'identity',        gitRepo: 'https://github.com/example/user-directory',     status: 'active',                      platforms: { intPlatform: 'backend-int-cluster',  uatPlatform: 'backend-uat-cluster',  prdPlatform: 'backend-prd-cluster'  }, urls: { intUrl: 'https://gw-int-userdir.intranet.example.com',    uatUrl: 'https://gw-uat-userdir.intranet.example.com',    prdUrl: 'https://gw-prd-userdir.intranet.example.com'    }, probeHealth: '/health',                                                                                            tags: { criticality: 'medium', pillar: 'security' }, javaVersion: '17', javaComplianceStatus: 'compliant',     artifactoryUrl: ART('user-directory'), xrayUrl: XRAY('user-directory'), compositionViewerUrl: COMP('user-directory'), splunkUrl: SPLK('user-directory') },
  { appId: 'sso-bridge',         squadKey: 'identity',        gitRepo: 'https://github.com/example/sso-bridge',         status: 'inactive',                    platforms: { intPlatform: 'backend-int-cluster'  },                                                                          urls: { intUrl: 'https://gw-int-sso.intranet.example.com'                                                          },                                probeHealth: '/health',                                                                                            tags: { criticality: 'low',    pillar: 'security' }, javaVersion: '11', javaComplianceStatus: 'non-compliant', artifactoryUrl: ART('sso-bridge'),     xrayUrl: XRAY('sso-bridge'),     compositionViewerUrl: COMP('sso-bridge'),     splunkUrl: SPLK('sso-bridge') },
  // search
  { appId: 'search-api',         squadKey: 'search',          gitRepo: 'https://github.com/example/search-api',         status: 'active',                      platforms: { intPlatform: 'backend-int-cluster',  uatPlatform: 'backend-uat-cluster',  prdPlatform: 'backend-prd-cluster'  }, urls: { intUrl: 'https://gw-int-search.intranet.example.com',     uatUrl: 'https://gw-uat-search.intranet.example.com',     prdUrl: 'https://gw-prd-search.intranet.example.com'     }, probeHealth: '/health',                                    probeReadiness: '/health/readiness', tags: { criticality: 'high',   pillar: 'discovery' }, javaVersion: '17', javaComplianceStatus: 'compliant',     artifactoryUrl: ART('search-api'),     xrayUrl: XRAY('search-api'),     compositionViewerUrl: COMP('search-api'),     splunkUrl: SPLK('search-api') },
  { appId: 'indexer',            squadKey: 'search',          gitRepo: 'https://github.com/example/indexer',            status: 'active',                      platforms: { intPlatform: 'backend-int-cluster',                                      prdPlatform: 'backend-prd-cluster'  }, urls: { intUrl: 'https://gw-int-indexer.intranet.example.com',                                                      prdUrl: 'https://gw-prd-indexer.intranet.example.com'    }, probeHealth: '/health',                                                                                            tags: { criticality: 'medium', pillar: 'discovery' }, javaVersion: '17', javaComplianceStatus: 'compliant',     artifactoryUrl: ART('indexer'),        xrayUrl: XRAY('indexer'),        compositionViewerUrl: COMP('indexer'),        splunkUrl: SPLK('indexer') },
  { appId: 'search-suggest',     squadKey: 'search',          gitRepo: 'https://github.com/example/search-suggest',     status: 'active',                      platforms: { intPlatform: 'backend-int-gcp',      uatPlatform: 'backend-uat-gcp',      prdPlatform: 'backend-prd-gcp'      }, urls: { intUrl: 'https://gw-int-suggest.example.com',             uatUrl: 'https://gw-uat-suggest.example.com',             prdUrl: 'https://gw-prd-suggest.example.com'             }, probeHealth: '/health',                                                                                            tags: { criticality: 'medium', pillar: 'discovery' },                                                              compositionViewerUrl: COMP('search-suggest'),                                         splunkUrl: SPLK('search-suggest') },
  // recommendations
  { appId: 'recs-api',           squadKey: 'recommendations', gitRepo: 'https://github.com/example/recs-api',           status: 'active',                      platforms: { intPlatform: 'backend-int-cluster',  uatPlatform: 'backend-uat-cluster',  prdPlatform: 'backend-prd-cluster'  }, urls: { intUrl: 'https://gw-int-recs-api.intranet.example.com',   uatUrl: 'https://gw-uat-recs-api.intranet.example.com',   prdUrl: 'https://gw-prd-recs-api.intranet.example.com'   }, probeHealth: '/health', probeInfo: '/info',   probeLiveness: '/health/liveness', probeReadiness: '/health/readiness', tags: { criticality: 'high',   pillar: 'discovery' }, javaVersion: '17', javaComplianceStatus: 'compliant',     artifactoryUrl: ART('recs-api'),       xrayUrl: XRAY('recs-api'),       compositionViewerUrl: COMP('recs-api'),       splunkUrl: SPLK('recs-api') },
  { appId: 'recs-feature-store', squadKey: 'recommendations', gitRepo: 'https://github.com/example/recs-feature-store', status: 'active',                      platforms: { devPlatform: 'backend-dev-gcp',      intPlatform: 'backend-int-gcp',      uatPlatform: 'backend-uat-gcp',  prdPlatform: 'backend-prd-gcp' }, urls: { devUrl: 'https://gw-dev-feature-store.example.com', intUrl: 'https://gw-int-feature-store.example.com', uatUrl: 'https://gw-uat-feature-store.example.com', prdUrl: 'https://gw-prd-feature-store.example.com' }, probeHealth: '/health',                                    probeReadiness: '/health/ready',     tags: { criticality: 'medium', pillar: 'discovery' },                                                              compositionViewerUrl: COMP('recs-feature-store'),                                     splunkUrl: SPLK('recs-feature-store') },
  { appId: 'ranking-trainer',    squadKey: 'recommendations', gitRepo: 'https://github.com/example/ranking-trainer',    status: 'active',                      platforms: { devPlatform: 'data-pipeline-dev',    intPlatform: 'data-pipeline-int',    uatPlatform: 'data-pipeline-uat', prdPlatform: 'data-pipeline-prd' }, urls: {},                                                                                                                                                           probeHealth: '/health',                                                                                            tags: { criticality: 'medium', pillar: 'discovery', kind: 'batch' },                                               compositionViewerUrl: COMP('ranking-trainer'),                                        splunkUrl: SPLK('ranking-trainer') },
  { appId: 'recs-admin',         squadKey: 'recommendations', gitRepo: 'https://github.com/example/recs-admin',         status: 'inactive',                    platforms: { uatPlatform: 'frontend-uat-cluster'  },                                                                         urls: { uatUrl: 'https://gw-uat-recs-admin.intranet.example.com'                                                   },                                probeHealth: '/healthz',                                                                                           tags: { criticality: 'low',    pillar: 'discovery' } },
  // mobile
  { appId: 'ios-app',            squadKey: 'mobile',          gitRepo: 'https://github.com/example/ios-app',            status: 'active',                      platforms: {},                                                                                                               urls: {},                                                                                                                                                                                                                                                             tags: { criticality: 'high',   pillar: 'apps', store: 'app-store' },                                               compositionViewerUrl: COMP('ios-app') },
  { appId: 'android-app',        squadKey: 'mobile',          gitRepo: 'https://github.com/example/android-app',        status: 'active',                      platforms: {},                                                                                                               urls: {},                                                                                                                                                                                                                                                             tags: { criticality: 'high',   pillar: 'apps', store: 'play-store' },                                             compositionViewerUrl: COMP('android-app') },
  { appId: 'mobile-bff',         squadKey: 'mobile',          gitRepo: 'https://github.com/example/mobile-bff',         status: 'active',                      platforms: { intPlatform: 'backend-int-cluster',  uatPlatform: 'backend-uat-cluster',  prdPlatform: 'backend-prd-cluster'  }, urls: { intUrl: 'https://gw-int-mobile-bff.intranet.example.com', uatUrl: 'https://gw-uat-mobile-bff.intranet.example.com', prdUrl: 'https://gw-prd-mobile-bff.intranet.example.com' }, probeHealth: '/health',                                    probeReadiness: '/health/readiness', tags: { criticality: 'high',   pillar: 'apps' },                                                                  compositionViewerUrl: COMP('mobile-bff'),                                             splunkUrl: SPLK('mobile-bff') },
  // web
  { appId: 'marketing-site',     squadKey: 'web',             gitRepo: 'https://github.com/example/marketing-site',     status: 'active',                      platforms: { uatPlatform: 'frontend-uat-cluster',                                     prdPlatform: 'frontend-prd-cluster' }, urls: { uatUrl: 'https://gw-uat-marketing.intranet.example.com',                                                    prdUrl: 'https://example.com'                            }, probeHealth: '/healthz',                                                                                           tags: { criticality: 'medium', pillar: 'apps' },                                                                   compositionViewerUrl: COMP('marketing-site'),                                         splunkUrl: SPLK('marketing-site') },
  { appId: 'customer-portal',    squadKey: 'web',             gitRepo: 'https://github.com/example/customer-portal',    status: 'active',                      platforms: { uatPlatform: 'frontend-uat-cluster',                                     prdPlatform: 'frontend-prd-cluster' }, urls: { uatUrl: 'https://gw-uat-portal.intranet.example.com',                                                       prdUrl: 'https://gw-prd-portal.intranet.example.com'    }, probeHealth: '/healthz',                                                                                           tags: { criticality: 'high',   pillar: 'apps' },                                                                   compositionViewerUrl: COMP('customer-portal'),                                        splunkUrl: SPLK('customer-portal') },
  { appId: 'legacy-cms',         squadKey: 'web',             gitRepo: 'https://github.com/example/legacy-cms',         status: 'failed',                      platforms: { prdPlatform: 'frontend-prd-cluster'  },                                                                         urls: { prdUrl: 'https://gw-prd-cms.intranet.example.com'                                                          },                                probeHealth: '/healthz',                                                                                           tags: { criticality: 'low',    pillar: 'apps', incident: 'INC-9923' },                                            compositionViewerUrl: COMP('legacy-cms'),                                             splunkUrl: SPLK('legacy-cms') },
  // data-platform — Scala/Java batch jobs
  { appId: 'datalake-loader',    squadKey: 'data-platform',   gitRepo: 'https://github.com/example/datalake-loader',    status: 'active',                      platforms: { devPlatform: 'data-pipeline-dev',    intPlatform: 'data-pipeline-int',    uatPlatform: 'data-pipeline-uat', prdPlatform: 'data-pipeline-prd' }, urls: {},                                                                                                                                                           probeHealth: '/health',                                                                                            tags: { criticality: 'high',   pillar: 'data', kind: 'batch' },   javaVersion: '17', javaComplianceStatus: 'compliant',     artifactoryUrl: ART('datalake-loader'), xrayUrl: XRAY('datalake-loader'),compositionViewerUrl: COMP('datalake-loader'), splunkUrl: SPLK('datalake-loader') },
  { appId: 'kafka-bridge',       squadKey: 'data-platform',   gitRepo: 'https://github.com/example/kafka-bridge',       status: 'active',                      platforms: { intPlatform: 'backend-int-cluster',  uatPlatform: 'backend-uat-cluster',  prdPlatform: 'backend-prd-cluster'  }, urls: { intUrl: 'https://gw-int-kafka.intranet.example.com',                                                        prdUrl: 'https://gw-prd-kafka.intranet.example.com'     }, probeHealth: '/health',                                                                                            tags: { criticality: 'high',   pillar: 'data' },     javaVersion: '17', javaComplianceStatus: 'compliant',     artifactoryUrl: ART('kafka-bridge'),   xrayUrl: XRAY('kafka-bridge'),   compositionViewerUrl: COMP('kafka-bridge'),   splunkUrl: SPLK('kafka-bridge') },
  { appId: 'dbt-runner',         squadKey: 'data-platform',   gitRepo: 'https://github.com/example/dbt-runner',         status: 'active',                      platforms: { devPlatform: 'data-pipeline-dev',    intPlatform: 'data-pipeline-int',                                          prdPlatform: 'data-pipeline-prd' }, urls: {},                                                                                                                                              probeHealth: '/health',                                                                                            tags: { criticality: 'medium', pillar: 'data', kind: 'batch' },                                                    compositionViewerUrl: COMP('dbt-runner'),                                             splunkUrl: SPLK('dbt-runner') },
  // analytics
  { appId: 'looker-metrics',     squadKey: 'analytics',       gitRepo: 'https://github.com/example/looker-metrics',     status: 'active',                      platforms: { prdPlatform: 'backend-prd-gcp'      },                                                                          urls: { prdUrl: 'https://gw-prd-looker.example.com'                                                                },                                probeHealth: '/health',                                                                                            tags: { criticality: 'medium', pillar: 'data' },                                                                   compositionViewerUrl: COMP('looker-metrics'),                                         splunkUrl: SPLK('looker-metrics') },
  { appId: 'events-pipeline',    squadKey: 'analytics',       gitRepo: 'https://github.com/example/events-pipeline',    status: 'active',                      platforms: { intPlatform: 'data-pipeline-int',    uatPlatform: 'data-pipeline-uat',    prdPlatform: 'data-pipeline-prd'    }, urls: {},                                                                                                                                                           probeHealth: '/health',                                                                                            tags: { criticality: 'high',   pillar: 'data', kind: 'stream' },                                                  compositionViewerUrl: COMP('events-pipeline'),                                        splunkUrl: SPLK('events-pipeline') },
  { appId: 'ab-results-worker',  squadKey: 'analytics',       gitRepo: 'https://github.com/example/ab-results-worker',  status: 'active',                      platforms: { intPlatform: 'data-pipeline-int',                                         prdPlatform: 'data-pipeline-prd'    }, urls: {},                                                                                                                                                           probeHealth: '/health',                                                                                            tags: { criticality: 'medium', pillar: 'data' },                                                                   compositionViewerUrl: COMP('ab-results-worker'),                                      splunkUrl: SPLK('ab-results-worker') },
  // notifications — Java 17
  { appId: 'email-worker',       squadKey: 'notifications',   gitRepo: 'https://github.com/example/email-worker',       status: 'active',                      platforms: { intPlatform: 'backend-int-gcp',      uatPlatform: 'backend-uat-gcp',      prdPlatform: 'backend-prd-gcp'      }, urls: { intUrl: 'https://gw-int-email.example.com',               uatUrl: 'https://gw-uat-email.example.com',               prdUrl: 'https://gw-prd-email.example.com'               }, probeHealth: '/health',                                    probeReadiness: '/health/readiness', tags: { criticality: 'high',   pillar: 'messaging' }, javaVersion: '17', javaComplianceStatus: 'compliant',     artifactoryUrl: ART('email-worker'),   xrayUrl: XRAY('email-worker'),   compositionViewerUrl: COMP('email-worker'),   splunkUrl: SPLK('email-worker') },
  { appId: 'sms-gateway',        squadKey: 'notifications',   gitRepo: 'https://github.com/example/sms-gateway',        status: 'active',                      platforms: { intPlatform: 'backend-int-gcp',      uatPlatform: 'backend-uat-gcp',      prdPlatform: 'backend-prd-gcp'      }, urls: { intUrl: 'https://gw-int-sms.example.com',                 uatUrl: 'https://gw-uat-sms.example.com',                 prdUrl: 'https://gw-prd-sms.example.com'                 }, probeHealth: '/health',                                                                                            tags: { criticality: 'high',   pillar: 'messaging' }, javaVersion: '17', javaComplianceStatus: 'compliant',     artifactoryUrl: ART('sms-gateway'),    xrayUrl: XRAY('sms-gateway'),    compositionViewerUrl: COMP('sms-gateway'),    splunkUrl: SPLK('sms-gateway') },
  { appId: 'push-hub',           squadKey: 'notifications',   gitRepo: 'https://github.com/example/push-hub',           status: 'active',                      platforms: { intPlatform: 'backend-int-gcp',      uatPlatform: 'backend-uat-gcp',      prdPlatform: 'backend-prd-gcp'      }, urls: { intUrl: 'https://gw-int-push.example.com',                uatUrl: 'https://gw-uat-push.example.com',                prdUrl: 'https://gw-prd-push.example.com'                }, probeHealth: '/health',                                                                                            tags: { criticality: 'medium', pillar: 'messaging' },                                                              compositionViewerUrl: COMP('push-hub'),                                               splunkUrl: SPLK('push-hub') },
  { appId: 'legacy-pager',       squadKey: 'notifications',   gitRepo: 'https://github.com/example/legacy-pager',       status: 'marked-for-decommissioning',  platforms: { prdPlatform: 'backend-prd-cluster'  },                                                                          urls: { prdUrl: 'https://gw-prd-pager.intranet.example.com'                                                        },                                probeHealth: '/health',                                                                                            tags: { criticality: 'low',    sunset: '2026-Q2' },   javaVersion: '8',  javaComplianceStatus: 'exempt',                                                                                                                                          splunkUrl: SPLK('legacy-pager') },
  // observability — Java 17
  { appId: 'log-pipeline',       squadKey: 'observability',   gitRepo: 'https://github.com/example/log-pipeline',       status: 'active',                      platforms: { intPlatform: 'backend-int-cluster',                                      prdPlatform: 'backend-prd-cluster'  }, urls: { intUrl: 'https://gw-int-logs.intranet.example.com',                                                         prdUrl: 'https://gw-prd-logs.intranet.example.com'      }, probeHealth: '/health',                                                                                            tags: { criticality: 'high',   pillar: 'platform' }, javaVersion: '17', javaComplianceStatus: 'compliant',     artifactoryUrl: ART('log-pipeline'),   xrayUrl: XRAY('log-pipeline'),   compositionViewerUrl: COMP('log-pipeline'),   splunkUrl: SPLK('log-pipeline') },
  { appId: 'metrics-agent',      squadKey: 'observability',   gitRepo: 'https://github.com/example/metrics-agent',      status: 'active',                      platforms: { localPlatform: 'backend-local-cluster', intPlatform: 'backend-int-cluster', prdPlatform: 'backend-prd-cluster' }, urls: {},                                                                                                                                                          probeHealth: '/health',                                                                                            tags: { criticality: 'high',   pillar: 'platform' }, javaVersion: '17', javaComplianceStatus: 'compliant',     artifactoryUrl: ART('metrics-agent'),  xrayUrl: XRAY('metrics-agent'),  compositionViewerUrl: COMP('metrics-agent'),  splunkUrl: SPLK('metrics-agent') },
  { appId: 'trace-collector',    squadKey: 'observability',   gitRepo: 'https://github.com/example/trace-collector',    status: 'active',                      platforms: { intPlatform: 'backend-int-cluster',  uatPlatform: 'backend-uat-cluster',  prdPlatform: 'backend-prd-cluster'  }, urls: { intUrl: 'https://gw-int-traces.intranet.example.com',                                                       prdUrl: 'https://gw-prd-traces.intranet.example.com'    }, probeHealth: '/health',                                                                                            tags: { criticality: 'medium', pillar: 'platform' }, javaVersion: '17', javaComplianceStatus: 'compliant',     artifactoryUrl: ART('trace-collector'),xrayUrl: XRAY('trace-collector'),compositionViewerUrl: COMP('trace-collector'), splunkUrl: SPLK('trace-collector') },
  // devex
  { appId: 'ci-runner',          squadKey: 'devex',           gitRepo: 'https://github.com/example/ci-runner',          status: 'active',                      platforms: { prdPlatform: 'backend-prd-cluster'  },                                                                          urls: { prdUrl: 'https://gw-prd-ci.intranet.example.com'                                                           },                                probeHealth: '/health',                                                                                            tags: { criticality: 'high',   pillar: 'platform' },                                                               compositionViewerUrl: COMP('ci-runner'),                                              splunkUrl: SPLK('ci-runner') },
  { appId: 'build-cache',        squadKey: 'devex',           gitRepo: 'https://github.com/example/build-cache',        status: 'active',                      platforms: { prdPlatform: 'backend-prd-cluster'  },                                                                          urls: { prdUrl: 'https://gw-prd-cache.intranet.example.com'                                                        },                                probeHealth: '/health',                                                                                            tags: { criticality: 'medium', pillar: 'platform' },                                                               compositionViewerUrl: COMP('build-cache'),                                            splunkUrl: SPLK('build-cache') },
  { appId: 'cli-tools',          squadKey: 'devex',           gitRepo: 'https://github.com/example/cli-tools',          status: 'active',                      platforms: {},                                                                                                               urls: {},                                                                                                                                                                                                                                                             tags: { criticality: 'medium', pillar: 'platform', kind: 'cli' },                                                  compositionViewerUrl: COMP('cli-tools') },
  // fraud — Java 11 (non-compliant, upgrade planned)
  { appId: 'risk-api',           squadKey: 'fraud',           gitRepo: 'https://github.com/example/risk-api',           status: 'active',                      platforms: { intPlatform: 'backend-int-cluster',  uatPlatform: 'backend-uat-cluster',  prdPlatform: 'backend-prd-cluster'  }, urls: { intUrl: 'https://gw-int-risk.intranet.example.com',       uatUrl: 'https://gw-uat-risk.intranet.example.com',       prdUrl: 'https://gw-prd-risk.intranet.example.com'       }, probeHealth: '/health',                                    probeReadiness: '/health/readiness', tags: { criticality: 'high',   pillar: 'security' }, javaVersion: '11', javaComplianceStatus: 'non-compliant', artifactoryUrl: ART('risk-api'),       xrayUrl: XRAY('risk-api'),       compositionViewerUrl: COMP('risk-api'),       splunkUrl: SPLK('risk-api') },
  { appId: 'rules-engine',       squadKey: 'fraud',           gitRepo: 'https://github.com/example/rules-engine',       status: 'active',                      platforms: { intPlatform: 'backend-int-cluster',  uatPlatform: 'backend-uat-cluster',  prdPlatform: 'backend-prd-cluster'  }, urls: { intUrl: 'https://gw-int-rules.intranet.example.com',      uatUrl: 'https://gw-uat-rules.intranet.example.com',      prdUrl: 'https://gw-prd-rules.intranet.example.com'      }, probeHealth: '/health',                                                                                            tags: { criticality: 'high',   pillar: 'security' }, javaVersion: '11', javaComplianceStatus: 'non-compliant', artifactoryUrl: ART('rules-engine'),   xrayUrl: XRAY('rules-engine'),   compositionViewerUrl: COMP('rules-engine'),   splunkUrl: SPLK('rules-engine') },
  { appId: 'fraud-legacy',       squadKey: 'fraud',           gitRepo: 'https://github.com/example/fraud-legacy',       status: 'marked-for-decommissioning',  platforms: { prdPlatform: 'backend-prd-cluster'  },                                                                          urls: { prdUrl: 'https://gw-prd-fraud-legacy.intranet.example.com'                                                 },                                probeHealth: '/healthz',                                                                                           tags: { criticality: 'low',    sunset: '2026-Q3' },   javaVersion: '8',  javaComplianceStatus: 'exempt',                                                                                                                                          splunkUrl: SPLK('fraud-legacy') },
  // support-tools
  { appId: 'agent-console',      squadKey: 'support-tools',   gitRepo: 'https://github.com/example/agent-console',      status: 'active',                      platforms: { uatPlatform: 'frontend-uat-cluster',                                     prdPlatform: 'frontend-prd-cluster' }, urls: { uatUrl: 'https://gw-uat-agent.intranet.example.com',                                                        prdUrl: 'https://gw-prd-agent.intranet.example.com'     }, probeHealth: '/healthz',                                                                                           tags: { criticality: 'medium', pillar: 'apps' },                                                                   compositionViewerUrl: COMP('agent-console'),                                          splunkUrl: SPLK('agent-console') },
  { appId: 'case-manager',       squadKey: 'support-tools',   gitRepo: 'https://github.com/example/case-manager',       status: 'active',                      platforms: { intPlatform: 'backend-int-cluster',  uatPlatform: 'backend-uat-cluster',  prdPlatform: 'backend-prd-cluster'  }, urls: { intUrl: 'https://gw-int-cases.intranet.example.com',      uatUrl: 'https://gw-uat-cases.intranet.example.com',      prdUrl: 'https://gw-prd-cases.intranet.example.com'      }, probeHealth: '/health',                                                                                            tags: { criticality: 'medium', pillar: 'apps' },       javaVersion: '17', javaComplianceStatus: 'compliant',     artifactoryUrl: ART('case-manager'),   xrayUrl: XRAY('case-manager'),   compositionViewerUrl: COMP('case-manager'),   splunkUrl: SPLK('case-manager') },
  { appId: 'broken-old-tool',    squadKey: 'support-tools',   gitRepo: 'https://github.com/example/broken-old-tool',    status: 'failed',                      platforms: { intPlatform: 'backend-int-cluster'  },                                                                          urls: { intUrl: 'https://gw-int-broken.intranet.example.com'                                                       },                                probeHealth: '/health',                                                                                            tags: { criticality: 'low',    incident: 'INC-9912' }, javaVersion: '8', javaComplianceStatus: 'exempt',                                                                                                                                          splunkUrl: SPLK('broken-old-tool') },
  // growth
  { appId: 'ab-test-service',    squadKey: 'growth',          gitRepo: 'https://github.com/example/ab-test-service',    status: 'active',                      platforms: { intPlatform: 'backend-int-cluster',  uatPlatform: 'backend-uat-cluster',  prdPlatform: 'backend-prd-cluster'  }, urls: { intUrl: 'https://gw-int-ab.intranet.example.com',         uatUrl: 'https://gw-uat-ab.intranet.example.com',         prdUrl: 'https://gw-prd-ab.intranet.example.com'         }, probeHealth: '/health',                                    probeReadiness: '/health/readiness', tags: { criticality: 'medium', pillar: 'growth' },                                                                 compositionViewerUrl: COMP('ab-test-service'),                                        splunkUrl: SPLK('ab-test-service') },
  { appId: 'feature-flags',      squadKey: 'growth',          gitRepo: 'https://github.com/example/feature-flags',      status: 'active',                      platforms: { intPlatform: 'backend-int-cluster',  uatPlatform: 'backend-uat-cluster',  prdPlatform: 'backend-prd-cluster'  }, urls: { intUrl: 'https://gw-int-flags.intranet.example.com',      uatUrl: 'https://gw-uat-flags.intranet.example.com',      prdUrl: 'https://gw-prd-flags.intranet.example.com'      }, probeHealth: '/health',                                                                                            tags: { criticality: 'high',   pillar: 'growth' },                                                                compositionViewerUrl: COMP('feature-flags'),                                          splunkUrl: SPLK('feature-flags') },
  { appId: 'legacy-flags',       squadKey: 'growth',          gitRepo: 'https://github.com/example/legacy-flags',       status: 'inactive',                    platforms: { prdPlatform: 'backend-prd-cluster'  },                                                                          urls: { prdUrl: 'https://gw-prd-flags-old.intranet.example.com'                                                    },                                probeHealth: '/health',                                                                                            tags: { criticality: 'low',    pillar: 'growth' },    javaVersion: '8',  javaComplianceStatus: 'exempt',                                                                                                                                          splunkUrl: SPLK('legacy-flags') },
  { appId: 'legacy-feature-flags', squadKey: 'growth',        gitRepo: 'https://github.com/example/legacy-feature-flags', status: 'marked-for-decommissioning', platforms: { intPlatform: 'frontend-uat-cluster',                                     prdPlatform: 'frontend-prd-cluster' }, urls: { intUrl: 'https://gw-int-flags-old-ui.intranet.example.com',                                                 prdUrl: 'https://gw-prd-flags-old-ui.intranet.example.com' }, probeHealth: '/health',                                                                                          tags: { criticality: 'low',    sunset: '2026-Q4' } },
] as const;

// ── Deployment events (from appstatus.yaml) ───────────────────────────────────

const DEPLOYS: Array<{
  appId: string; env: string; version: string; commitId: string; branch: string;
  deployedBy: string; state: DeployState; deployedAt: string;
  notes?: string; xray?: string; javaVersion?: string; javaComplianceStatus?: string; changeRequest?: string;
}> = [
  { appId: 'recs-api',      env: 'prd', version: '1.4.0', commitId: 'a1b2c3d', branch: 'main',           deployedBy: 'alice@example.com', state: 'success',    deployedAt: '2026-03-12T08:30:00.000Z', xray: 'https://xray.example.com/recs-api/1.4.0', javaVersion: '17', javaComplianceStatus: 'compliant' },
  { appId: 'recs-api',      env: 'prd', version: '1.4.1', commitId: 'b2c3d4e', branch: 'main',           deployedBy: 'bob@example.com',   state: 'success',    deployedAt: '2026-03-19T08:30:00.000Z' },
  { appId: 'recs-api',      env: 'prd', version: '1.4.2', commitId: 'c3d4e5f', branch: 'main',           deployedBy: 'carol@example.com', state: 'failed',     deployedAt: '2026-03-26T08:30:00.000Z', notes: 'memory regression detected by canary' },
  { appId: 'recs-api',      env: 'prd', version: '1.4.1', commitId: 'b2c3d4e', branch: 'main',           deployedBy: 'carol@example.com', state: 'rolledback', deployedAt: '2026-03-26T08:45:00.000Z', notes: 'auto-rollback to 1.4.1' },
  { appId: 'recs-api',      env: 'uat', version: '1.4.3-rc1', commitId: 'd4e5f6g', branch: 'release/1.4.3', deployedBy: 'alice@example.com', state: 'pending',   deployedAt: '2026-04-22T10:00:00.000Z' },
  { appId: 'payments-api',  env: 'int', version: '2.0.0-rc3', commitId: '9aa8bb7', branch: 'release/2.0', deployedBy: 'priya@example.com', state: 'success',    deployedAt: '2026-04-10T09:00:00.000Z' },
  { appId: 'payments-api',  env: 'uat', version: '2.0.0-rc3', commitId: '9aa8bb7', branch: 'release/2.0', deployedBy: 'priya@example.com', state: 'success',    deployedAt: '2026-04-15T09:00:00.000Z' },
  { appId: 'payments-api',  env: 'prd', version: '1.9.7',     commitId: '7eed889', branch: 'main',        deployedBy: 'tom@example.com',   state: 'success',    deployedAt: '2026-04-08T11:30:00.000Z', xray: 'https://xray.example.com/payments-api/1.9.7', javaVersion: '21', javaComplianceStatus: 'compliant', changeRequest: 'CR-2026-0408-payments' },
  { appId: 'auth-gateway',  env: 'prd', version: '3.2.1',     commitId: 'f1e2d3c', branch: 'main',        deployedBy: 'clara@example.com', state: 'success',    deployedAt: '2026-04-01T07:00:00.000Z' },
  { appId: 'auth-gateway',  env: 'prd', version: '3.2.2',     commitId: 'deadbee', branch: 'main',        deployedBy: 'ben@example.com',   state: 'pending',    deployedAt: '2026-04-25T06:00:00.000Z', notes: 'blue-green cutover in progress' },
  { appId: 'ios-app',       env: 'prd', version: '5.10.0',    commitId: 'ios0510', branch: 'main',        deployedBy: 'ema@example.com',   state: 'success',    deployedAt: '2026-04-18T16:00:00.000Z', notes: 'App Store release' },
  { appId: 'android-app',   env: 'prd', version: '5.10.0',    commitId: 'and0510', branch: 'main',        deployedBy: 'finn@example.com',  state: 'success',    deployedAt: '2026-04-19T11:00:00.000Z', notes: 'Play Store release' },
  { appId: 'risk-api',      env: 'int', version: '0.9.4',     commitId: 'risk094', branch: 'feat/score-v3', deployedBy: 'ami@example.com', state: 'success',    deployedAt: '2026-04-20T08:00:00.000Z' },
  { appId: 'risk-api',      env: 'uat', version: '0.9.4',     commitId: 'risk094', branch: 'feat/score-v3', deployedBy: 'ami@example.com', state: 'success',    deployedAt: '2026-04-22T08:00:00.000Z' },
  { appId: 'risk-api',      env: 'prd', version: '0.9.4',     commitId: 'risk094', branch: 'feat/score-v3', deployedBy: 'ami@example.com', state: 'pending',    deployedAt: '2026-04-25T08:00:00.000Z', notes: 'awaiting approval', xray: 'https://xray.example.com/risk-api/0.9.4', javaVersion: '11', javaComplianceStatus: 'non-compliant', changeRequest: 'CR-2026-0425-risk' },
  { appId: 'feature-flags', env: 'dev', version: 'snapshot',  commitId: 'ff-dev-1', branch: 'feat/percent-rollout', deployedBy: 'per@example.com', state: 'success', deployedAt: '2026-04-24T15:30:00.000Z' },
  { appId: 'feature-flags', env: 'dev', version: 'snapshot',  commitId: 'ff-dev-2', branch: 'feat/percent-rollout', deployedBy: 'per@example.com', state: 'failed',  deployedAt: '2026-04-25T07:00:00.000Z', notes: 'schema migration failed in dev DB' },
  { appId: 'broken-old-tool', env: 'int', version: '0.0.1',   commitId: 'ancient', branch: 'master',      deployedBy: 'jak@example.com',   state: 'failed',     deployedAt: '2025-11-15T22:00:00.000Z', notes: 'tracked for retirement', javaVersion: '8', javaComplianceStatus: 'exempt' },
];

// ── Main ──────────────────────────────────────────────────────────────────────

async function seedAiops() {
  await connectRedis();
  console.log('Seeding AIOps data (infra clusters + apps + deployments)...');

  // 1. Infra clusters
  for (const c of INFRA_CLUSTERS) {
    await infraService.create({ ...c, tags: JSON.stringify(c.tags) });
  }
  console.log(` infra clusters  ${INFRA_CLUSTERS.length}`);

  // 2. Apps — resolve squad key to squadId
  let appCount = 0;
  let skipped  = 0;
  for (const a of APP_DEFS) {
    const squad = await squadService.findByKey(a.squadKey);
    if (!squad) { console.warn(`  WARNING: squad key '${a.squadKey}' not found, skipping ${a.appId}`); skipped++; continue; }
    await appService.create({
      appId:                a.appId,
      gitRepo:              a.gitRepo,
      squadId:              squad.id,
      squadKey:             a.squadKey,
      status:               a.status as any,
      tags:                 a.tags as Record<string, string>,
      platforms:            a.platforms as Record<string, string>,
      urls:                 a.urls as Record<string, string>,
      probeHealth:          (a as any).probeHealth          ?? '',
      probeInfo:            (a as any).probeInfo            ?? '',
      probeLiveness:        (a as any).probeLiveness        ?? '',
      probeReadiness:       (a as any).probeReadiness       ?? '',
      javaVersion:          (a as any).javaVersion          ?? '',
      javaComplianceStatus: (a as any).javaComplianceStatus ?? '',
      artifactoryUrl:       (a as any).artifactoryUrl       ?? '',
      xrayUrl:              (a as any).xrayUrl              ?? '',
      compositionViewerUrl: (a as any).compositionViewerUrl ?? '',
      splunkUrl:            (a as any).splunkUrl            ?? '',
    });
    appCount++;
  }
  console.log(` apps            ${appCount}${skipped ? ` (${skipped} skipped — run seed.ts first)` : ''}`);

  // 3. Deployment events (replayed in order = appstatus.yaml order)
  for (const d of DEPLOYS) {
    await appstatusService.record(d.appId, d.env, d);
  }
  console.log(` deploy events   ${DEPLOYS.length}`);

  console.log('\nAIOps seed complete.');
  process.exit(0);
}

seedAiops().catch((err) => { console.error(err); process.exit(1); });
